import { Box, Grid } from '@mui/material'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'
import AppHeader from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<Box
					sx={{
						minHeight: '100vh',
						display: 'flex',
						flexDirection: 'column',
					}}
				>
					<AppHeader />
					<Box
						sx={{
							margin: 'auto',
							flex: '1',
							maxWidth: '1200px',
							width: {
								lg: '1200px',
								xs: '100%',
							},
						}}
					>
						{children}
					</Box>
				</Box>
			</body>
		</html>
	)
}
